DATASET_DIR = "data/dataset"
QUERIES_DIR = "data/queries"

ORB_NFEATURES = 1000
RATIO_TEST = 0.75
TOP_K = 5

RANSAC_REPROJ_THRESHOLD = 5.0
MIN_INLIERS = 10

MIN_FINAL_SCORE = 0.15
MIN_INLIERS_STRICT = 12
